[tool.poetry]
name = "cryptohgraphy"
version = "0.1.0"
description = ""
authors = ["dmarek03 <domarek@student.agh.edu.pl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
notebook = "^7.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
